DROP DATABASE IF EXISTS DBemployee;

CREATE DATABASE DBemployee;

USE DBemployee;

CREATE TABLE department (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE roles (
    id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(30) NOT NULL,
    salary DECIMAL NOT NULL,
    department_id INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE employee (
    id INT NOT NULL AUTO_INCREMENT,
    first VARCHAR(30) NOT NULL,
    last VARCHAR(30) NOT NULL,
    role INT NOT NULL,
    ID INT NULL,
    PRIMARY KEY (id)
);